import subprocess
import logging
import requests
import re
from datetime import datetime
from PySide6.QtCore import QObject, Qt, QTimer, Signal, QUrl
from PySide6.QtWebEngineCore import QWebEngineProfile, QWebEnginePage
from PySide6.QtWebEngineWidgets import QWebEngineView
import json
from PySide6.QtWidgets import QMessageBox, QListWidgetItem
from PySide6.QtGui import QPixmap, QIcon

from backend.library import LibraryManager
from ViGaVault_utils import build_scanner_config, get_db_path, translator, QtLogSignal, QtLogHandler
from ViGaVault_workers import FullScanWorker

class SilentWebEnginePage(QWebEnginePage):
    """WHY: Suppresses harmless but terrifying JavaScript console errors generated by external trackers."""
    def javaScriptConsoleMessage(self, level, message, lineNumber, sourceID):
        pass

class HeadlessAmazonScanner(QObject):
    finished = Signal(list)
    progress = Signal(str)
    error = Signal(str)

    def __init__(self, parent=None):
        super().__init__(parent)
        from dialogs.login_browser_dialog import get_amazon_profile
        self.profile = get_amazon_profile()
        
        # Attach to the main window as parent to inherit its native window handle.
        # This guarantees that the Chromium process is spawned and JavaScript execution is never throttled.
        main_win = parent.mw if parent and hasattr(parent, 'mw') else None
        self.browser = QWebEngineView(main_win)
        self.browser.hide()
        
        self.page = SilentWebEnginePage(self.profile, self.browser)
        self.browser.setPage(self.page)
        
        self.poll_timer = QTimer(self)
        self.poll_timer.setInterval(1000)
        self.poll_timer.timeout.connect(self.poll_js_state)
        
        self.region_code = "US"
        self.csrf_not_found_ticks = 0

    def start_scan(self, region_code="US"):
        self.region_code = region_code
        self.csrf_not_found_ticks = 0
        self.vgv_scan_routed = False
        from backend.amazon.login_amazon import get_region_config
        config = get_region_config(region_code)
        
        url = f"https://{config.lunaDomain}/"
        self.browser.load(QUrl(url))
        # WHY: Start the 1-second polling timer so poll_js_state checks page states and executes the scan.
        self.poll_timer.start()

    def stop_scan(self):
        self.poll_timer.stop()
        self.browser.triggerAction(QWebEnginePage.WebAction.Stop)

    def clean_up(self):
        self.poll_timer.stop()
        if hasattr(self, 'browser') and self.browser is not None:
            self.browser.stop()
            self.browser.setParent(None)
            self.browser.deleteLater()
            self.browser = None
        if hasattr(self, 'page') and self.page is not None:
            self.page.setParent(None)
            self.page.deleteLater()
            self.page = None

    def poll_js_state(self):
        current_year = datetime.now().year
        
        js = """
        (function() {
            try {
                if (window.vgvScanFailed) {
                    return JSON.stringify({ status: "error", error: window.vgvScanError });
                }
                
                if (window.vgvClaims) {
                    return JSON.stringify({ status: "success", claims: window.vgvClaims });
                }
                
                if (window.vgvScanning) {
                    return JSON.stringify({ status: "scanning", progress: window.vgvProgress });
                }

                var url = window.location.href;
                if (!url.startsWith('http')) {
                    return JSON.stringify({ status: "waiting_domain", progress: "Waiting for Amazon domain to load..." });
                }

                var pathname = window.location.pathname;
                if (url.includes('/ap/') || url.includes('signin') || pathname.includes('/ap/')) {
                    return JSON.stringify({ status: "error", error: "Amazon connection has expired or is invalid. It needs to be re-applied in the Platform Manager." });
                }
                
                if (pathname.includes('/claims/claims/')) {
                    window.location.href = '/claims/my-collection';
                    return JSON.stringify({ status: "routing", progress: "Routing to collection page..." });
                }
                
                if (!pathname.includes('/claims/my-collection')) {
                    if (!window.vgvScanRouted) {
                        window.vgvScanRouted = true;
                        window.location.href = '/claims/my-collection';
                        return JSON.stringify({ status: "routing", progress: "Routing to collection page..." });
                    } else {
                        // We already routed to my-collection but got kicked back to home/signin. The session has expired!
                        return JSON.stringify({ status: "error", error: "Amazon session expired. Please reconnect in Platform Manager." });
                    }
                }

                var csrfInput = document.querySelector('input[name="csrf-key"]');
                if (!csrfInput || !csrfInput.value) {
                    return JSON.stringify({ status: "waiting_csrf", progress: "Waiting for Amazon CSRF..." });
                }
                
                window.vgvScanning = true;
                window.vgvClaims = null;
                window.vgvProgress = "Starting Amazon library scan...";
                
                (async function() {
                    try {
                        var csrfToken = csrfInput.value;
                        var allClaims = [];
                        var graph_ql_query = `fragment Claims_Item_Media on Media {
  alt
  description
  defaultMedia {
    ...MediaAsset
    __typename
  }
  desktop {
    ...MediaAsset
    __typename
  }
  tablet {
    ...MediaAsset
    __typename
  }
  videoPlaceholderImage {
    ...MediaAsset
    __typename
  }
  __typename
}

fragment Claims_Item on Item {
  id
  grantsCode
  isFGWP
  requiresLinkBeforeClaim
  isDirectEntitlement
  supportedSurfaces
  isDeepLink
  assets {
    id
    title
    platforms
    claimInstructions
    mobileClaimInstructions
    claimVisualInstructions {
      ...Claims_Item_Media
      __typename
    }
    thumbnailImage {
      ...Claims_Item_Media
      __typename
    }
    cardMedia {
      ...Claims_Item_Media
      __typename
    }
    redemptionPlatforms
    __typename
  }
  game {
    id
    isActiveAndVisible
    assets {
      title
      publisher
      __typename
    }
    __typename
  }
  offers {
    id
    endTime
    __typename
  }
  siblingExternalLinkAssets {
    id
    title
    cardMedia {
      ...Claims_Item_Media
      __typename
    }
    __typename
  }
  __typename
}

fragment Claims_Claim on Claim {
  orderId
  itemId
  offerId
  itemTitle
  destinationAccount
  destinationAccountType
  orderState
  orderCreationDate
  fulfillmentInfo {
    deliveryStatus
    fulfillmentLastUpdatedDate
    claimCode
    deepLinkUrl
    __typename
  }
  item {
    ...Claims_Item
    __typename
  }
  __typename
}

query ClaimsContextQuery($filters: ClaimFilters, $nextToken: String, $pageSize: Int) {
  claims(filters: $filters, nextToken: $nextToken, pageSize: $pageSize) {
    claims {
      ...Claims_Claim
      __typename
    }
    nextToken
    __typename
  }
}

fragment MediaAsset on MediaAsset {
  src1x
  src2x
  type
  __typename
}`;
                        var queryStr = graph_ql_query;
                        
                        // WHY: Fetch the complete catalog in a single dynamic background pass.
                        // We query from the current year, which chronologically encompasses all historical claims.
                        var year = new Date().getFullYear();
                        var nextToken = null;
                        var hasNextPage = true;
                        var pageNum = 1;
                        
                        while (hasNextPage) {
                            window.vgvProgress = "Fetching Amazon Games (Page " + pageNum + ")...";
                            
                            // Use official variable payload (no pageSize override)
                            var variables = { 
                                "filters": { 
                                    "endDate": year + "-12-31T23:00:00Z"
                                }
                            };
                            if (nextToken) variables.nextToken = nextToken;
                            var payload = { "operationName": "ClaimsContextQuery", "variables": variables, "extensions": {}, "query": queryStr };

                            var response = await fetch('/graphql', {
                                method: 'POST',
                                credentials: 'same-origin',
                                headers: { 'Content-Type': 'application/json', 'csrf-token': csrfToken },
                                body: JSON.stringify(payload)
                            });

                            if (!response.ok) {
                                var errText = "";
                                try { errText = await response.text(); } catch(e) {}
                                window.vgvScanFailed = true;
                                window.vgvScanError = "GraphQL HTTP " + response.status + " - " + errText;
                                return;
                            }

                            var data = await response.json();
                            if (data.errors) {
                                window.vgvScanFailed = true;
                                window.vgvScanError = "GraphQL errors: " + JSON.stringify(data.errors);
                                return;
                            }
                            var claimsData = data.data && data.data.claims;

                            if (claimsData && claimsData.claims) {
                                allClaims = allClaims.concat(claimsData.claims);
                                nextToken = claimsData.nextToken;
                                if (!nextToken) hasNextPage = false;
                            } else {
                                hasNextPage = false;
                            }
                            pageNum++;
                        }
                        
                        // Deduplicate claims by item ID to guarantee no duplicate processing if there is overlapping pagination
                        var uniqueClaims = [];
                        var seenIds = new Set();
                        for (var c of allClaims) {
                            if (c && c.item && c.item.id) {
                                if (!seenIds.has(c.item.id)) {
                                    seenIds.add(c.item.id);
                                    uniqueClaims.push(c);
                                }
                            }
                        }
                        
                        window.vgvClaims = uniqueClaims;
                    } catch(e) {
                        window.vgvScanFailed = true;
                        window.vgvScanError = e.toString();
                    }
                })();
                
                return JSON.stringify({ status: "scanning", progress: window.vgvProgress });
            } catch(e) {
                return JSON.stringify({ status: "error", error: e.toString() });
            }
        })();
        """
        self.page.runJavaScript(js, 0, self.on_js_result)

    def on_js_result(self, result):
        if not result or not isinstance(result, str):
            # WHY: Silence raw browser progress stdout print to avoid console clutter.
            # print("[AMAZON SCAN] WebEngine initializing. Waiting for page context...")
            return
            
        try:
            result = json.loads(result)
        except Exception as e:
            # WHY: Silence raw error parsing print as we handle failures cleanly via Qt signals.
            # print(f"[AMAZON SCAN] ERROR parsing JS result: {e}")
            return
            
        status = result.get("status")
        progress = result.get("progress", "")
        
        if status == "waiting_domain":
            # WHY: Silenced to keep console logs completely clean and free of unaligned strings.
            # print(f"[AMAZON SCAN] {progress}")
            self.progress.emit(progress)
        elif status == "routing":
            # WHY: Silenced to keep console logs completely clean and free of unaligned strings.
            # print(f"[AMAZON SCAN] {progress}")
            self.progress.emit(progress)
        elif status == "waiting_csrf":
            # WHY: Silenced to keep console logs completely clean and free of unaligned strings.
            # print(f"[AMAZON SCAN] {progress}")
            self.csrf_not_found_ticks += 1
            if self.csrf_not_found_ticks > 25:
                self.poll_timer.stop()
                # WHY: Silenced to prevent cluttering stdout before emitting clean UI error.
                # print("[AMAZON SCAN] Session expired or invalid.")
                self.error.emit("Amazon session expired. Please reconnect in Platform Manager.")
            else:
                self.progress.emit(progress)
        elif status == "scanning":
            # WHY: Silenced to prevent verbose page-by-page scraping progress from cluttering terminal logs.
            # print(f"[AMAZON SCAN] {progress}")
            self.progress.emit(progress)
        elif status == "error":
            self.poll_timer.stop()
            err_msg = result.get("error", "Unknown script error")
            # WHY: Silenced to keep console logs completely clean and rely strictly on self.error signal.
            # print(f"[AMAZON SCAN] ERROR: {err_msg}")
            self.error.emit(err_msg)
        elif status == "success":
            self.poll_timer.stop()
            claims = result.get("claims") or []
            # print(f"[AMAZON SCAN] Headless fetch completed. Retrieved {len(claims)} raw claims.")
            self.finished.emit(claims)

class ScanController(QObject):
    def __init__(self, main_window):
        super().__init__(main_window)
        self.mw = main_window
        self.log_signal = None
        self.qt_log_handler = None

    def update_sync_log(self, message):
        # WHY: Allow the user to pause auto-scrolling by moving the scrollbar up.
        # Auto-scrolling only triggers if the scrollbar was already at/near the bottom.
        scrollbar = self.mw.sidebar.scan_results.verticalScrollBar()
        was_at_bottom = scrollbar.value() >= scrollbar.maximum() - 4

        # WHY: Targeted Update - Dynamically animates the log by replacing the text of the last item in place.
        if message.startswith("UI_START|"):
            clean_msg = message.replace("UI_START|", "")
            self.mw.sidebar.scan_results.addItem(clean_msg)
            if was_at_bottom:
                self.mw.sidebar.scan_results.scrollToBottom()
        elif message.startswith("UI_UPDATE|"):
            clean_msg = message.replace("UI_UPDATE|", "")
            if self.mw.sidebar.scan_results.count() > 0:
                last_item = self.mw.sidebar.scan_results.item(self.mw.sidebar.scan_results.count() - 1)
                last_item.setText(clean_msg)
                if was_at_bottom:
                    self.mw.sidebar.scan_results.scrollToBottom()
        else:
            self.mw.sidebar.scan_results.addItem(message)
            if was_at_bottom:
                self.mw.sidebar.scan_results.scrollToBottom()

    def open_scan_settings(self):
        # WHY: Roll up the filters smoothly instead of making them vanish abruptly.
        self.mw.filter_controller.set_filters_ui_state(False)
        self.mw.sidebar.scan_panel.hide()
        self.mw.sidebar.scan_settings_panel.show()
        # WHY: Share the stretch factor so the settings panel perfectly fills the gap left by the rolled-up filters.
        self.mw.sidebar.layout.setStretchFactor(self.mw.sidebar.scan_panel, 0)
        self.mw.sidebar.layout.setStretchFactor(self.mw.sidebar.scan_settings_panel, 1)
        self.mw.sidebar.btn_scan_settings.setEnabled(False)

    def close_scan_settings(self):
        self.mw.sidebar.scan_settings_panel.hide()
        self.mw.sidebar.layout.setStretchFactor(self.mw.sidebar.scan_settings_panel, 0)
        # Unroll filters
        self.mw.filter_controller.set_filters_ui_state(True)
        self.mw.sidebar.btn_scan_settings.setEnabled(True)

    def start_full_scan(self):
        if self.mw.full_scan_in_progress:
            QMessageBox.information(self.mw, "Info", translator.tr("msg_task_in_progress"))
            return
            
        # WHY: Interactive Prerequisite Checks. Since the button is always enabled, 
        # we explicitly audit the environment here and popup a warning guiding the user if something is missing.
        igdb_connected = getattr(self.mw, 'igdb_connected_cache', False)
        if not igdb_connected:
            QMessageBox.warning(self.mw, "IGDB Required", translator.tr("msg_scan_disabled_igdb"))
            if hasattr(self.mw, 'menu_controller'):
                self.mw.menu_controller.open_settings(tab_index=2)
            return

        has_source = self.mw.sidebar.chk_scan_galaxy.isChecked() or self.mw.sidebar.chk_scan_gog_web.isChecked() or self.mw.sidebar.chk_scan_epic.isChecked() or self.mw.sidebar.chk_scan_steam.isChecked() or self.mw.sidebar.chk_scan_local.isChecked()
        has_dl_images = self.mw.sidebar.chk_scan_dl_images.isChecked()
        if not has_source and not has_dl_images:
            QMessageBox.warning(self.mw, translator.tr("scan_settings_title"), translator.tr("msg_scan_disabled_source"))
            # WHY: Auto-open the scan settings panel so the user knows exactly where to look.
            self.open_scan_settings()
            return

        try:
            output = subprocess.check_output('tasklist', shell=True).decode(errors='ignore')
            if "GalaxyClient.exe" in output:
                reply = QMessageBox.question(self.mw, "Galaxy Client Detected",
                                            "The Galaxy Client is running. It must be closed to access the database.\n\nPlease close it and click Yes.",
                                            QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
                if reply == QMessageBox.No: return
        except: pass

        self.mw.full_scan_in_progress = True
        self.mw.sidebar.scan_settings_panel.hide()
        self.mw.sidebar.btn_scan_settings.setEnabled(False)
        self.mw.sidebar.btn_full_scan.setEnabled(False)
        self.mw.sidebar.btn_full_scan.setText(translator.tr("sidebar_btn_scanning"))
        if hasattr(self.mw.sidebar, 'combo_view_mode'):
            self.mw.sidebar.combo_view_mode.setEnabled(False)
        self.mw.sidebar.chk_scan_galaxy.setEnabled(False)
        self.mw.sidebar.chk_scan_gog_web.setEnabled(False)
        self.mw.sidebar.chk_scan_epic.setEnabled(False)
        self.mw.sidebar.chk_scan_steam.setEnabled(False)
        self.mw.sidebar.chk_scan_amazon.setEnabled(False)
        self.mw.sidebar.chk_scan_local.setEnabled(False)
        self.mw.sidebar.chk_scan_dl_images.setEnabled(False)
        self.mw.filter_controller.set_filters_ui_state(False)

        self.mw.sidebar.scan_panel.show()
        self.mw.sidebar.scan_title_label.setText(translator.tr("sidebar_scan_title_full"))
        self.mw.sidebar.scan_input.hide()
        self.mw.sidebar.scan_btn.hide()
        self.mw.sidebar.scan_limit_combo.hide()
        self.mw.sidebar.scan_go_wild.hide()
        self.mw.sidebar.btn_confirm.hide()
        self.mw.sidebar.btn_cancel.setText(translator.tr("sidebar_btn_stop"))
        self.mw.sidebar.scan_results.clear()

        try: self.mw.sidebar.btn_cancel.clicked.disconnect()
        except: pass
        self.mw.sidebar.btn_cancel.clicked.connect(self.stop_full_scan)

        self.log_signal = QtLogSignal()
        self.log_signal.message_written.connect(self.update_sync_log)
        self.qt_log_handler = QtLogHandler(self.log_signal)
        logging.getLogger().addHandler(self.qt_log_handler)

        do_galaxy = self.mw.sidebar.chk_scan_galaxy.isChecked()
        do_gog_web = self.mw.sidebar.chk_scan_gog_web.isChecked()
        do_epic = self.mw.sidebar.chk_scan_epic.isChecked()
        do_steam = self.mw.sidebar.chk_scan_steam.isChecked()
        do_amazon = self.mw.sidebar.chk_scan_amazon.isChecked()
        do_local = self.mw.sidebar.chk_scan_local.isChecked()
        do_dl_images = self.mw.sidebar.chk_scan_dl_images.isChecked()
        
        target_folders = []
        for folder, chk in self.mw.sidebar.chk_scan_folders.items():
            if chk.isChecked(): target_folders.append(folder)

        # WHY: Print the pre-scan checklist first so the user gets immediate visual confirmation
        # of the active storefront targets before any headless scans are spawned.
        temp_config = build_scanner_config()
        temp_config['enable_galaxy_db'] = do_galaxy
        temp_config['enable_gog_web'] = do_gog_web
        temp_config['enable_epic_web'] = do_epic
        temp_config['enable_steam_web'] = do_steam
        temp_config['enable_amazon_web'] = do_amazon
        temp_config['download_images'] = do_dl_images
        temp_config['images_only'] = not any([do_galaxy, do_local, do_gog_web, do_epic, do_steam, do_amazon]) and do_dl_images
        if 'local_scan_config' not in temp_config:
            temp_config['local_scan_config'] = {}
        temp_config['local_scan_config']['enable_local_scan'] = do_local
        
        from backend.library import get_pre_scan_checklist_text
        checklist_text = get_pre_scan_checklist_text(temp_config)
        
        now_str = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        if temp_config['images_only']:
            logging.info(f"[{now_str}] \n{' STANDALONE MEDIA BACKFILL STARTED ':=^80}")
        else:
            logging.info(f"[{now_str}] \n{' FULL INTELLIGENT SCAN STARTED ':=^80}")
        logging.info(checklist_text + "\n")

        # Create Automatic Pre-Scan Backup
        try:
            from backend.backup_manager import create_vgv_backup
            from ViGaVault_utils import get_db_path
            import os
            db_path = get_db_path()
            backup_dir = os.path.join(os.path.dirname(db_path), "backups")
            os.makedirs(backup_dir, exist_ok=True)
            backup_path = os.path.join(backup_dir, "VGV-DB_Pre_Scan.vgv")
            # Only backup the DB itself to keep the process instantaneous
            create_vgv_backup(db_path, "", {}, {}, backup_path)
            logging.info(f"Automated pre-scan database backup saved to: {backup_path}\n")
        except Exception as e:
            logging.error(f"Failed to create pre-scan backup: {e}")


            
        if do_amazon:
            # WHY: Print the primary AMAZON SCAN header block immediately to the console terminal
            # before initializing the WebEngine browser. This gives the user instant confirmation
            # that the scan has successfully started since spawning the headless engine takes time.
            from ViGaVault_utils import format_header_row
            logging.info(format_header_row("AMAZON SCAN", is_secondary=False, col_spec=[17, 36, 23]))

            # RATIONALE: We completely remove any .addItem progress prints to keep the sidebar
            # list widget 100% clean of raw browser progress logs, displaying only clean Unicode borders!
            
            from backend.amazon.login_amazon import get_amazon_region
            region = get_amazon_region()
            
            self.amazon_scanner = HeadlessAmazonScanner(self)
            
            def on_amazon_progress(msg):
                # RATIONALE: Kept completely silent to avoid polluting the app screen list widget.
                pass
                
            def on_amazon_error(err):
                logging.error(f"[AMAZON SCAN] {err}")
                self.mw.sidebar.scan_results.addItem(f"ERROR: {err}")
                self.mw.sidebar.scan_results.scrollToBottom()
                self.amazon_scanner.clean_up()
                self.amazon_scanner.deleteLater()
                self.amazon_scanner = None
                self.run_remaining_full_scan(do_galaxy, do_local, do_gog_web, do_epic, do_steam, False, None, do_dl_images, target_folders)
                
            def on_amazon_finished(claims):
                self.amazon_scanner.clean_up()
                self.amazon_scanner.deleteLater()
                self.amazon_scanner = None
                
                # WHY: Immediately run Python sync year-by-year for all claims on the active database in-memory,
                # saving results to disk and printing the clean Unicode box rows sequentially in real-time.
                from backend.amazon.sync_amazon import sync_amazon_database
                from ViGaVault_utils import build_scanner_config
                cfg = build_scanner_config()
                
                if not hasattr(self, 'temp_manager'):
                    from backend.library import LibraryManager
                    self.temp_manager = LibraryManager(cfg)
                    self.temp_manager.load_db()
                    
                changes, stats = sync_amazon_database(
                    cfg, self.temp_manager.games, claims, 
                    print_header=False, print_report=True
                )
                if changes:
                    self.temp_manager.save_db()
                
                # WHY: Run remaining storefront scans, passing accumulated claims and stats to the worker thread.
                self.run_remaining_full_scan(
                    do_galaxy, do_local, do_gog_web, do_epic, do_steam, True, 
                    claims, do_dl_images, target_folders,
                    amazon_stats=stats
                )
                
            self.amazon_scanner.progress.connect(on_amazon_progress)
            self.amazon_scanner.error.connect(on_amazon_error)
            self.amazon_scanner.finished.connect(on_amazon_finished)
            self.amazon_scanner.start_scan(region)
        else:
            self.run_remaining_full_scan(do_galaxy, do_local, do_gog_web, do_epic, do_steam, False, None, do_dl_images, target_folders)

    def run_remaining_full_scan(self, do_galaxy, do_local, do_gog_web, do_epic, do_steam, do_amazon, amazon_claims, do_dl_images, target_folders, amazon_stats=None):
        self.full_scan_worker = FullScanWorker(
            do_galaxy=do_galaxy,
            do_local=do_local,
            do_gog_web=do_gog_web,
            do_epic=do_epic,
            do_steam=do_steam,
            do_amazon=do_amazon,
            amazon_claims=amazon_claims,
            amazon_stats=amazon_stats, # WHY: Pass the accumulated Amazon stats to the background worker thread.
            do_download_images=do_dl_images,
            target_folders=target_folders,
            parent=self
        )
        self.full_scan_worker.finished.connect(self.finish_full_scan)
        self.full_scan_worker.renames_ready_signal.connect(self.handle_proposed_renames)
        self.full_scan_worker.start()

    def handle_proposed_renames(self, proposed_renames):
        from dialogs.rename_confirmation_dialog import RenameConfirmationDialog
        dlg = RenameConfirmationDialog(proposed_renames, self.mw)
        if dlg.exec():
            approved = dlg.get_approved_renames()
            if approved:
                self.mw.game_operations_controller.execute_batch_renames(approved)

    def stop_full_scan(self):
        if hasattr(self, 'amazon_scanner') and self.amazon_scanner:
            self.amazon_scanner.clean_up()
            self.amazon_scanner.deleteLater()
            self.amazon_scanner = None

        if self.mw.full_scan_in_progress:
            logging.info(f"{' Full Scan interrupted by user ':-^80}")
            if hasattr(self, 'full_scan_worker') and self.full_scan_worker:
                self.full_scan_worker.requestInterruption()
            else:
                self.finish_full_scan()
                self.mw.sidebar.scan_panel.hide()
                self.mw.filter_controller.set_filters_ui_state(True)
                self.restore_scan_panel()

    def finish_full_scan(self):
        logging.getLogger().removeHandler(self.qt_log_handler)
        
        self.mw.full_scan_in_progress = False
        self.mw.sidebar.btn_scan_settings.setEnabled(True)
        self.mw.sidebar.update_scan_button_state()
        self.mw.sidebar.btn_full_scan.setText(translator.tr("sidebar_btn_full_scan"))
        self.mw.sidebar.chk_scan_galaxy.setEnabled(True)
        self.mw.sidebar.chk_scan_gog_web.setEnabled(getattr(self.mw, 'gog_connected_cache', False))
        self.mw.sidebar.chk_scan_epic.setEnabled(getattr(self.mw, 'epic_connected_cache', False))
        self.mw.sidebar.chk_scan_steam.setEnabled(getattr(self.mw, 'steam_connected_cache', False))
        self.mw.sidebar.chk_scan_amazon.setEnabled(getattr(self.mw, 'amazon_connected_cache', False))
        self.mw.sidebar.chk_scan_local.setEnabled(True)
        self.mw.sidebar.chk_scan_dl_images.setEnabled(True)
        if hasattr(self.mw.sidebar, 'combo_view_mode'):
            self.mw.sidebar.combo_view_mode.setEnabled(True)

        if self.mw.sidebar.scan_panel.isVisible():
            self.mw.sidebar.scan_results.scrollToBottom()
            self.mw.sidebar.btn_cancel.setText(translator.tr("btn_close"))
            try: self.mw.sidebar.btn_cancel.clicked.disconnect()
            except: pass
            self.mw.sidebar.btn_cancel.clicked.connect(self.cancel_inline_scan)

        self.mw.sidebar.refresh_backup_button_text()
        self.mw.library_controller.refresh_data()

    def start_inline_scan(self, game_data):
        # WHY: Prevent manual scan operations from corrupting database or UI state while a full background scan is writing data.
        if self.mw.full_scan_in_progress:
            QMessageBox.warning(self.mw, "Warning", translator.tr("msg_wait_for_scan"))
            return
            
        self.mw.current_scan_game = game_data
        self.mw.sidebar.scan_panel.show()
        self.mw.sidebar.scan_settings_panel.hide()
        self.mw.filter_controller.set_filters_ui_state(False)
        
        # WHY: Explicitly wire the Cancel button to the inline scan closure logic. 
        # Since the Full Scan dynamically overwrites this button's connection, we must guarantee it is bound correctly here.
        try: self.mw.sidebar.btn_cancel.clicked.disconnect()
        except: pass
        self.mw.sidebar.btn_cancel.clicked.connect(self.cancel_inline_scan)
        
        # WHY: Disable the main scan UI elements during a manual scan to prevent accidental clicks and conflicting tasks.
        self.mw.sidebar.btn_full_scan.setEnabled(False)
        self.mw.sidebar.btn_scan_settings.setEnabled(False)
        self.mw.sidebar.chk_scan_galaxy.setEnabled(False)
        self.mw.sidebar.chk_scan_gog_web.setEnabled(False)
        self.mw.sidebar.chk_scan_epic.setEnabled(False)
        self.mw.sidebar.chk_scan_steam.setEnabled(False)
        self.mw.sidebar.chk_scan_amazon.setEnabled(False)
        self.mw.sidebar.chk_scan_local.setEnabled(False)
        
        self.restore_scan_panel()
        
        raw_name = game_data.get('Folder_Name', '')
        clean_name = re.sub(r'^\d{4}\s*-\s*', '', raw_name)
        clean_name = re.sub(r'\s*\([^)]*\)$', '', clean_name).strip()
        self.mw.sidebar.scan_input.setText(clean_name)
        
        self.mw.sidebar.scan_results.clear()
        item = QListWidgetItem(translator.tr("sidebar_log_searching"))
        item.setTextAlignment(Qt.AlignCenter)
        item.setFlags(item.flags() & ~Qt.ItemIsEnabled)
        self.mw.sidebar.scan_results.addItem(item)
        self.mw.sidebar.scan_input.setFocus()

        QTimer.singleShot(50, self.run_inline_search)

    def on_manual_search_trigger(self):
        self.mw.sidebar.scan_results.clear()
        item = QListWidgetItem(translator.tr("sidebar_log_searching"))
        item.setTextAlignment(Qt.AlignCenter)
        item.setFlags(item.flags() & ~Qt.ItemIsEnabled)
        self.mw.sidebar.scan_results.addItem(item)
        QTimer.singleShot(50, self.run_inline_search)

    def run_inline_search(self):
        term = self.mw.sidebar.scan_input.text()
        if not term: return
        
        if not self.mw.current_scan_game:
            QMessageBox.warning(self.mw, "Error", "No game selected for scanning. Please click the scan icon on a game.")
            return
        
        manager = LibraryManager(build_scanner_config())
        manager.load_db()
        token = manager.get_access_token()

        limit = int(self.mw.sidebar.scan_limit_combo.currentText())
        go_wild = self.mw.sidebar.scan_go_wild.isChecked()
        candidates = manager.fetch_candidates(token, term, limit=limit, go_wild=go_wild)
        
        self.mw.sidebar.scan_results.clear()
        for g in candidates:
            year = ''
            if 'release_dates' in g and g['release_dates']:
                dates = [d['date'] for d in g['release_dates'] if 'date' in d]
                if dates:
                    try: year = datetime.utcfromtimestamp(min(dates)).strftime('%Y')
                    except Exception: pass

            display_text = g.get('name', 'Unknown')
            if year: display_text = f"{year} - {display_text}"

            item = QListWidgetItem(display_text)
            item.setData(Qt.UserRole, g)
            
            if 'cover' in g and 'url' in g['cover']:
                try:
                    img_url = "https:" + g['cover']['url'].replace("t_thumb", "t_cover_small")
                    data = requests.get(img_url, timeout=2).content
                    pix = QPixmap()
                    pix.loadFromData(data)
                    item.setIcon(QIcon(pix))
                except Exception: pass
            self.mw.sidebar.scan_results.addItem(item)

        if not candidates:
            item = QListWidgetItem(translator.tr("sidebar_log_no_results"))
            item.setFlags(item.flags() & ~Qt.ItemIsEnabled)
            self.mw.sidebar.scan_results.addItem(item)

    def restore_scan_panel(self):
        self.mw.sidebar.scan_title_label.setText(translator.tr("sidebar_manual_scan_title"))
        self.mw.sidebar.scan_input.show()
        self.mw.sidebar.scan_btn.show()
        self.mw.sidebar.scan_limit_combo.setCurrentText("10")
        self.mw.sidebar.scan_limit_combo.show()
        self.mw.sidebar.scan_go_wild.setChecked(False)
        self.mw.sidebar.scan_go_wild.show()
        self.mw.sidebar.btn_confirm.show()
        self.mw.sidebar.btn_cancel.setText(translator.tr("sidebar_manual_scan_cancel_btn"))

    def cancel_inline_scan(self):
        self.mw.sidebar.scan_panel.hide()
        self.mw.filter_controller.set_filters_ui_state(True)
        
        # WHY: Targeted Update - Restore the main scan UI elements based on their configured global state.
        self.mw.sidebar.btn_scan_settings.setEnabled(True)
        self.mw.sidebar.update_scan_button_state()
        config = build_scanner_config()
        self.mw.sidebar.chk_scan_galaxy.setEnabled(config.get('enable_galaxy_db', True))
        self.mw.sidebar.chk_scan_gog_web.setEnabled(getattr(self.mw, 'gog_connected_cache', False))
        self.mw.sidebar.chk_scan_epic.setEnabled(getattr(self.mw, 'epic_connected_cache', False))
        self.mw.sidebar.chk_scan_steam.setEnabled(getattr(self.mw, 'steam_connected_cache', False))
        self.mw.sidebar.chk_scan_amazon.setEnabled(getattr(self.mw, 'amazon_connected_cache', False))
        self.mw.sidebar.chk_scan_local.setEnabled(config.get('local_scan_config', {}).get('enable_local_scan', True))
        self.mw.sidebar.chk_scan_dl_images.setEnabled(True)
        
        self.mw.sidebar.scan_results.clear()
        self.mw.sidebar.scan_input.clear()
        self.restore_scan_panel()

    def apply_inline_selection(self):
        item = self.mw.sidebar.scan_results.currentItem()
        if not item: return
        
        chosen_game = item.data(Qt.UserRole)
        manager = LibraryManager(build_scanner_config())
        manager.load_db()
        current_folder = self.mw.current_scan_game.get('Folder_Name')
        game_obj = manager.games.get(current_folder)
        
        # Check for duplicates before applying
        target_igdb_id = f"igdb_{chosen_game.get('id')}"
        conflict_folder = None
        for folder, g in manager.games.items():
            if folder == current_folder: continue
            ids = [x.strip() for x in str(g.data.get('game_ID', '')).split(',')]
            if target_igdb_id in ids:
                conflict_folder = folder
                break
                
        if conflict_folder:
            self.mw.execute_merge(conflict_folder, current_folder)
            self.cancel_inline_scan()
            return
        
        if game_obj.apply_candidate_data(chosen_game):
            while True:
                try:
                    manager.save_db()
                    break 
                except PermissionError:
                    reply = QMessageBox.warning(self.mw, "File Locked",
                                        translator.tr("msg_file_locked", db_path=get_db_path()),
                                        QMessageBox.Ok | QMessageBox.Cancel)
                    if reply == QMessageBox.Cancel:
                        return

            # WHY: Target update without reloading the entire UI.
            folder_name = self.mw.current_scan_game.get('Folder_Name')
            new_data = game_obj.to_dict()
            self.mw.library_controller.patch_memory_df(folder_name, new_data)
            self.mw.library_controller.update_status_checkboxes_state()
                
            self.mw.list_controller.update_single_card(folder_name, force_media_reload=True)
            self.mw.filter_controller.request_filter_update()
            
            self.mw.sidebar.scan_results.clear()
            item = QListWidgetItem(translator.tr("sidebar_log_update_complete"))
            item.setTextAlignment(Qt.AlignCenter)
            item.setFlags(item.flags() & ~Qt.ItemIsEnabled)
            self.mw.sidebar.scan_results.addItem(item)
            
            QTimer.singleShot(2000, self.cancel_inline_scan)

