# WHY: DRY Principle - A universal, fully isolated embedded browser for securely logging into any storefront.
import re
import time
import logging
from PySide6.QtWidgets import QDialog, QVBoxLayout, QApplication
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWebEngineCore import QWebEngineProfile, QWebEnginePage, QWebEngineSettings
from PySide6.QtCore import QUrl, QTimer, Qt
from ViGaVault_utils import DIALOG_STD_SIZE, center_window

class SilentWebEnginePage(QWebEnginePage):
    """WHY: Suppresses harmless but terrifying JavaScript console errors generated by external trackers."""
    def javaScriptConsoleMessage(self, level, message, lineNumber, sourceID):
        pass

class LoginBrowserDialog(QDialog):
    def __init__(self, start_url, target_cookies=None, success_url=None, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Secure Platform Login")
        self.resize(*DIALOG_STD_SIZE)
        center_window(self, parent)
        
        self.cookies = {}
        self.auth_code = None
        self.target_cookies = target_cookies or []
        self.success_url = success_url
        self.success_triggered = False
        self.boot_time = time.time()
        
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        
        self.browser = QWebEngineView()
        self.profile = QWebEngineProfile()
        
        # WHY: Explicitly force full capabilities so third-party CAPTCHAs (hCaptcha/Arkose) don't get blocked.
        settings = self.profile.settings()
        settings.setAttribute(QWebEngineSettings.LocalStorageEnabled, True)
        settings.setAttribute(QWebEngineSettings.JavascriptEnabled, True)
        settings.setAttribute(QWebEngineSettings.JavascriptCanOpenWindows, True)
        settings.setAttribute(QWebEngineSettings.AllowWindowActivationFromJavaScript, True)
        
        # WHY: hCaptcha's advanced bot detection compares the claimed Chrome version in the User-Agent 
        # against the actual JavaScript engine's physical capabilities. Hardcoding a fake version causes a mismatch 
        # resulting in "Incorrect response". We fetch the true engine UA and strictly strip the "QtWebEngine" tag.
        default_ua = self.profile.httpUserAgent()
        stealth_ua = re.sub(r'QtWebEngine/[\d\.]+\s', '', default_ua)
        self.profile.setHttpUserAgent(stealth_ua)
        
        self.cookie_store = self.profile.cookieStore()
        self.page = SilentWebEnginePage(self.profile, self.browser)
        # WHY: Explicitly make the profile a child of the page. This guarantees that the profile's memory outlives the page,
        # preventing the "Release of profile requested" C++ warning during shutdown by enforcing a clean destruction order.
        self.profile.setParent(self.page)
        
        # WHY: Off-The-Record profiles start completely empty in RAM, so we don't need deleteAllCookies().
        self.cookie_store.cookieAdded.connect(self.on_cookie_added)
        self.browser.setPage(self.page)
        self.browser.urlChanged.connect(self.on_url_changed)
        
        # WHY: No disk to wait for, so we can load the URL immediately.
        self.browser.load(QUrl(start_url))
        layout.addWidget(self.browser)

    def keyPressEvent(self, event):
        # WHY: QDialog inherently closes itself when Enter or Escape is pressed. 
        # We intercept and ignore these keys so that typing Enter in the Epic 
        # login forms submits the web form instead of violently terminating the dialog.
        if event.key() in (Qt.Key_Return, Qt.Key_Enter, Qt.Key_Escape):
            # WHY: Explicitly accept the event so it doesn't bubble up and accidentally trigger the parent dialog's default buttons.
            event.accept()
            return
        super().keyPressEvent(event)
        
    def on_cookie_added(self, cookie):
        name = cookie.name().data().decode('utf-8')
        val = cookie.value().data().decode('utf-8')
        self.cookies[name] = val
        
        # WHY: A persistent profile asynchronously loads old cookies from disk on boot.
        # To prevent instantly false-triggering on an old EPIC_SSO ghost cookie before deleteAllCookies() 
        # wipes it, we enforce a strict 3-second grace period. A human cannot solve an hCaptcha 
        # and log in within 3 seconds, so any target cookie arriving this early is definitively a ghost.
        if not self.success_triggered and name in self.target_cookies:
            time_passed = time.time() - self.boot_time
            if time_passed > 3.0:
                self.trigger_success()
            
    def on_url_changed(self, url):
        # WHY: Fallback success detection. If the user lands on their account page, we know they logged in successfully.
        url_str = url.toString()
        if not self.success_triggered and self.success_url and self.success_url in url_str:
            from urllib.parse import urlparse, parse_qs
            parsed_url = urlparse(url_str)
            
            # WHY: Ensure the success string is in the actual domain/path being visited, 
            # NOT just sitting inside the initial login URL's query parameters (like redirect_uri).
            active_page = f"{parsed_url.netloc}{parsed_url.path}"
            
            if self.success_url in active_page:
                qs = parse_qs(parsed_url.query)
                if 'code' in qs:
                    self.auth_code = qs['code'][0]
                self.trigger_success()
            
    def trigger_success(self):
        self.success_triggered = True
        # WHY: Wait 1.5 seconds before closing. This ensures all lingering cookies from the final HTTP response 
        # are fully intercepted and written to our dictionary before the web engine shuts down.
        QTimer.singleShot(1500, self.accept)
        
    def closeEvent(self, event):
        # WHY: Simplified cleanup. Qt's parent-child memory management will now handle the destruction
        # of the page and profile in the correct order when the dialog is deleted.
        self.browser.stop()
        super().closeEvent(event)