# WHY: DRY Principle - A universal, fully isolated embedded browser for securely logging into any storefront.
from PySide6.QtWidgets import QDialog, QVBoxLayout, QApplication
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWebEngineCore import QWebEngineProfile, QWebEnginePage
from PySide6.QtCore import QUrl, QTimer
from ViGaVault_utils import DIALOG_STD_SIZE, center_window

class SilentWebEnginePage(QWebEnginePage):
    """WHY: Suppresses harmless but terrifying JavaScript console errors generated by external trackers."""
    def javaScriptConsoleMessage(self, level, message, lineNumber, sourceID):
        pass

class LoginBrowserDialog(QDialog):
    def __init__(self, start_url, target_cookies=None, success_url=None, parent=None):
        # WHY: Pass None to explicitly break the C++ parent hierarchy. This prevents the Platform 
        # Manager from violently assassinating the Chromium process and causing the Windows HWND deadlock.
        super().__init__(None)
        self.setWindowTitle("Secure Platform Login")
        self.resize(*DIALOG_STD_SIZE)
        center_window(self, parent)
        
        self.cookies = {}
        self.auth_code = None
        self.target_cookies = target_cookies or []
        self.success_url = success_url
        self.success_triggered = False
        
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        
        self.browser = QWebEngineView()
        
        self.profile = QWebEngineProfile(self)
        
        self.cookie_store = self.profile.cookieStore()
        
        # WHY: Security & UX - Forcefully wipe the shared profile's memory every time the dialog opens. 
        # This ensures a "Disconnect" truly behaves like a logout and prevents previous sessions from auto-filling credentials.
        self.cookie_store.deleteAllCookies()
        self.cookie_store.cookieAdded.connect(self.on_cookie_added)
        
        self.page = SilentWebEnginePage(self.profile, self.browser)
        self.browser.setPage(self.page)
        self.browser.urlChanged.connect(self.on_url_changed)
        
        self.browser.load(QUrl(start_url))
        layout.addWidget(self.browser)
        
    def on_cookie_added(self, cookie):
        name = cookie.name().data().decode('utf-8')
        val = cookie.value().data().decode('utf-8')
        self.cookies[name] = val
        
        # WHY: Check against a list of valid authorization cookies.
        if not self.success_triggered and name in self.target_cookies:
            self.trigger_success()
            
    def on_url_changed(self, url):
        # WHY: Fallback success detection. If the user lands on their account page, we know they logged in successfully.
        url_str = url.toString()
        if not self.success_triggered and self.success_url and self.success_url in url_str:
            from urllib.parse import urlparse, parse_qs
            parsed_url = urlparse(url_str)
            
            # WHY: Ensure the success string is in the actual domain/path being visited, 
            # NOT just sitting inside the initial login URL's query parameters (like redirect_uri).
            active_page = f"{parsed_url.netloc}{parsed_url.path}"
            
            if self.success_url in active_page:
                qs = parse_qs(parsed_url.query)
                if 'code' in qs:
                    self.auth_code = qs['code'][0]
                self.trigger_success()
            
    def trigger_success(self):
        self.success_triggered = True
        # WHY: Wait 1.5 seconds before closing. This ensures all lingering cookies from the final HTTP response 
        # are fully intercepted and written to our dictionary before the web engine shuts down.
        QTimer.singleShot(1500, self.accept)
        
    def closeEvent(self, event):
        self.browser.stop()
        
        self.browser.setPage(None)
        if getattr(self, 'page', None):
            self.page.deleteLater()
            self.page = None
            
        if getattr(self, 'profile', None):
            # WHY: Sever the immediate C++ parent link and delay profile deletion until AFTER the event loop 
            # has successfully deleted the page. This permanently suppresses the Qt memory warning.
            self.profile.setParent(None)
            profile_obj = self.profile
            QTimer.singleShot(100, profile_obj.deleteLater)
            self.profile = None
        
        super().closeEvent(event)