# WHY: Single Responsibility Principle - Strictly manages Epic Games authentication states, 
# token exchanges, and secure local cookie storage without bleeding into the UI layer.
import os
import requests
import logging
from ViGaVault_utils import BASE_DIR, save_encrypted_json, load_encrypted_json

EPIC_DIR = os.path.join(BASE_DIR, "backend", "epic")
SESSION_FILE = os.path.join(EPIC_DIR, "epic_session.dat")

def is_epic_connected():
    """Checks if a valid session file exists for the Epic Games platform."""
    return os.path.exists(SESSION_FILE)

def disconnect_epic():
    """Safely removes the stored cookies and tokens, instantly logging the user out locally."""
    if os.path.exists(SESSION_FILE):
        try: os.remove(SESSION_FILE)
        except: pass

def save_epic_session(data_dict):
    """Securely dumps the OAuth tokens into a local JSON file."""
    os.makedirs(EPIC_DIR, exist_ok=True)
    save_encrypted_json(SESSION_FILE, data_dict)
        
def get_epic_session():
    """Returns the stored session data as a Python dictionary for the scanner to use."""
    return load_encrypted_json(SESSION_FILE)

def exchange_code_for_token(exchange_code):
    """WHY: Exchanges the browser authorization code for a persistent OAuth Bearer Token."""
    url = "https://account-public-service-prod.ol.epicgames.com/account/api/oauth/token"
    # WHY: Add Content-Type to strictly comply with OAuth2 form submission standards.
    headers = {
        "Authorization": "Basic MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y=",
        "Content-Type": "application/x-www-form-urlencoded"
    }
    # WHY: Match the exact grant_type generated by the redirect URL (authorization_code instead of exchange_code).
    payload = {"grant_type": "authorization_code", "code": exchange_code}
    try:
        resp = requests.post(url, headers=headers, data=payload, timeout=10)
        if resp.status_code == 200: return resp.json()
    except: pass
    return None

def refresh_epic_token():
    """WHY: Automatically requests a fresh 36-hour access token using the 1-year master refresh token."""
    session = get_epic_session()
    refresh_token = session.get("refresh_token")
    if not refresh_token: return None
    
    url = "https://account-public-service-prod.ol.epicgames.com/account/api/oauth/token"
    headers = {
        "Authorization": "Basic MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y=",
        "Content-Type": "application/x-www-form-urlencoded"
    }
    payload = {"grant_type": "refresh_token", "refresh_token": refresh_token}
    try:
        resp = requests.post(url, headers=headers, data=payload, timeout=10)
        if resp.status_code == 200:
            new_data = resp.json()
            save_epic_session(new_data)
            return new_data.get("access_token")
    except: pass
    return None